import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:mediscanai/models/reminder_model.dart';
import 'package:mediscanai/home_screen.dart';
import 'package:mediscanai/onboarding_screen.dart';
//import 'package:mediscanai/services/notification_service.dart';  +
import 'package:shared_preferences/shared_preferences.dart';

Future<void> main() async {
  // Ensure that Flutter bindings are initialized before any Flutter code runs.
  WidgetsFlutterBinding.ensureInitialized();
// test
  // Initialize Hive for local storage
  await Hive.initFlutter();
  // Register the adapter generated by the build_runner command
  Hive.registerAdapter(ReminderAdapter());
  // Open a box to store reminder objects
  await Hive.openBox<Reminder>('reminders');

  // Initialize our custom notification service
  //await NotificationService().init();              +

  // Check if the user has already seen the onboarding tutorial
  final prefs = await SharedPreferences.getInstance();
  final hasSeenOnboarding = prefs.getBool('hasSeenOnboarding') ?? false;

  runApp(MyApp(hasSeenOnboarding: hasSeenOnboarding));
}

class MyApp extends StatelessWidget {
  final bool hasSeenOnboarding;
  const MyApp({super.key, required this.hasSeenOnboarding});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MediScan',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.cyan,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        // Define a color scheme for consistency
        colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.cyan)
            .copyWith(secondary: Colors.redAccent),
      ),
      // Decide which screen to show based on whether onboarding is complete
      home: hasSeenOnboarding ? const HomeScreen() : const OnboardingScreen(),
    );
  }
}

